#pragma peephole off

#include "scn/step/enemy/Param.hpp"

using namespace scn::step::enemy;
using scn::step::enemy::Param;

void Param::exception(u32) { }

#define GET_ENEMY_PARAM_IMPL(enemy_name, offset) \
    enemy_name::Param* Param::enemy_name() const { \
        enemy_name##_.loadCheck(); \
        u8* head = reinterpret_cast<u8*>(enemy_name##_.mAccessor->get()->dataHeadAddress()); \
        u32 found = *reinterpret_cast<u32*>(head + offset); \
        if (found != 12345678) { \
            exception(found); \
        } \
        return reinterpret_cast<enemy_name::Param*>(head); \
    }

Param::Param()
    : common_("step/enemy/Common")
    , sirkibble_("step/enemy/Sirkibble")
    , brontoburt_("step/enemy/Brontoburt")
    , waddledee_("step/enemy/Waddledee")
    , bladeknight_("step/enemy/Bladeknight")
    , cappy_("step/enemy/Cappy")
    , hothead_("step/enemy/Hothead")
    , knucklejoe_("step/enemy/Knucklejoe")
    , puppetdee_("step/enemy/Puppetdee")
    , armordee_("step/enemy/Armordee")
    , como_("step/enemy/Como")
    , gordo_("step/enemy/Gordo")
    , whippy_("step/enemy/Whippy")
    , shotzo_("step/enemy/Shotzo")
    , leafan_("step/enemy/Leafan")
    , waddledoo_("step/enemy/Waddledoo")
    , bouncy_("step/enemy/Bouncy")
    , sparky_("step/enemy/Sparky")
    , needlous_("step/enemy/Needlous")
    , broomhatter_("step/enemy/Broomhatter")
    , scarfy_("step/enemy/Scarfy")
    , nruff_("step/enemy/Nruff")
    , flamer_("step/enemy/Flamer")
    , watergalbo_("step/enemy/Watergalbo")
    , rocky_("step/enemy/Rocky")
    , poppybrojr_("step/enemy/Poppybrojr")
    , noddy_("step/enemy/Noddy")
    , cerulean_("step/enemy/Cerulean")
    , blipper_("step/enemy/Blipper")
    , gigatzo_("step/enemy/Gigatzo")
    , sisterbound_("step/enemy/Sisterbound")
    , rollball_("step/enemy/Rollball")
    , mumbies_("step/enemy/Mumbies")
    , parasoldee_("step/enemy/Parasoldee")
    , kabu_("step/enemy/Kabu")
    , parasoldoo_("step/enemy/Parasoldoo")
    , foley_("step/enemy/Foley")
    , juckle_("step/enemy/Juckle")
    , bowby_("step/enemy/Bowby")
    , owgulf_("step/enemy/Owgulf")
    , degout_("step/enemy/Degout")
    , sheld_("step/enemy/Sheld")
    , lanzer_("step/enemy/Lanzer")
    , chilly_("step/enemy/Chilly")
    , tsukikage_("step/enemy/Tsukikage")
    , gemra_("step/enemy/Gemra")
    , sodory_("step/enemy/Sodory")
    , searches_("step/enemy/Searches")
    , pierce_("step/enemy/Pierce")
    , elec_("step/enemy/Elec")
    , snowl_("step/enemy/Snowl")
    , sun_("step/enemy/Sun")
    , sandbag_("step/enemy/Sandbag")
    , stareffect_("step/enemy/Stareffect")
    , cappyhat_("step/enemy/Cappyhat")
    , whispyapple_("step/enemy/Whispyapple")
    , parasol_("step/enemy/Parasol")
    , dubiorjr_("step/enemy/Dubiorjr")
    , poppybrojrbomb_("step/enemy/Poppybrojrbomb")
    , zankibblecutter_("step/enemy/Zankibblecutter")
    , bonkersbomb_("step/enemy/Bonkersbomb")
    , dubiorspark_("step/enemy/Dubiorspark")
    , mbossdead_("step/enemy/MBossDead")
{ }

GET_ENEMY_PARAM_IMPL(common, 0x98)
GET_ENEMY_PARAM_IMPL(sirkibble, 0x24)
GET_ENEMY_PARAM_IMPL(brontoburt, 0x60)
GET_ENEMY_PARAM_IMPL(waddledee, 0x84)
GET_ENEMY_PARAM_IMPL(bladeknight, 0x50)
GET_ENEMY_PARAM_IMPL(cappy, 0x38)
GET_ENEMY_PARAM_IMPL(hothead, 0x24)
GET_ENEMY_PARAM_IMPL(knucklejoe, 0x68)
// GET_ENEMY_PARAM_IMPL(puppetdee, ??)
// GET_ENEMY_PARAM_IMPL(armordee, ??)
GET_ENEMY_PARAM_IMPL(como, 0x4C)
GET_ENEMY_PARAM_IMPL(gordo, 0x24)
GET_ENEMY_PARAM_IMPL(whippy, 0x10)
GET_ENEMY_PARAM_IMPL(shotzo, 0x10)
GET_ENEMY_PARAM_IMPL(leafan, 0x34)
GET_ENEMY_PARAM_IMPL(waddledoo, 0x1C)
GET_ENEMY_PARAM_IMPL(bouncy, 0x38)
GET_ENEMY_PARAM_IMPL(sparky, 0x24)
GET_ENEMY_PARAM_IMPL(needlous, 0x48)
GET_ENEMY_PARAM_IMPL(broomhatter, 0x48)
GET_ENEMY_PARAM_IMPL(scarfy, 0xC8)
GET_ENEMY_PARAM_IMPL(nruff, 0x9C)
GET_ENEMY_PARAM_IMPL(flamer, 0x88)
GET_ENEMY_PARAM_IMPL(watergalbo, 0x18)
GET_ENEMY_PARAM_IMPL(rocky, 0xC4)
GET_ENEMY_PARAM_IMPL(poppybrojr, 0x28)
GET_ENEMY_PARAM_IMPL(noddy, 0xC)
GET_ENEMY_PARAM_IMPL(cerulean, 0x48)
GET_ENEMY_PARAM_IMPL(blipper, 0x64)
GET_ENEMY_PARAM_IMPL(gigatzo, 0x84)
GET_ENEMY_PARAM_IMPL(sisterbound, 0x48)
GET_ENEMY_PARAM_IMPL(rollball, 0x70)
GET_ENEMY_PARAM_IMPL(mumbies, 0x20)
GET_ENEMY_PARAM_IMPL(parasoldee, 0x7C)
GET_ENEMY_PARAM_IMPL(kabu, 0xB8)
GET_ENEMY_PARAM_IMPL(parasoldoo, 0x6C)
GET_ENEMY_PARAM_IMPL(foley, 0x5C)
GET_ENEMY_PARAM_IMPL(juckle, 0x54)
GET_ENEMY_PARAM_IMPL(bowby, 0x18)
GET_ENEMY_PARAM_IMPL(owgulf, 0x28)
GET_ENEMY_PARAM_IMPL(degout, 0x5C)
GET_ENEMY_PARAM_IMPL(sheld, 0x88)
GET_ENEMY_PARAM_IMPL(lanzer, 0x18)
GET_ENEMY_PARAM_IMPL(chilly, 0x2C)
GET_ENEMY_PARAM_IMPL(tsukikage, 0x90)
GET_ENEMY_PARAM_IMPL(gemra, 0x30)
GET_ENEMY_PARAM_IMPL(sodory, 0x48)
GET_ENEMY_PARAM_IMPL(searches, 0x18)
GET_ENEMY_PARAM_IMPL(pierce, 0x4C)
GET_ENEMY_PARAM_IMPL(elec, 0x64)
GET_ENEMY_PARAM_IMPL(snowl, 0x24)
GET_ENEMY_PARAM_IMPL(sun, 0x50)
GET_ENEMY_PARAM_IMPL(sandbag, 0xC)
GET_ENEMY_PARAM_IMPL(stareffect, 0x40)
// GET_ENEMY_PARAM_IMPL(cappyhat, ??)
GET_ENEMY_PARAM_IMPL(whispyapple, 0x88)
GET_ENEMY_PARAM_IMPL(parasol, 0x1C)
GET_ENEMY_PARAM_IMPL(dubiorjr, 0x1C)
GET_ENEMY_PARAM_IMPL(poppybrojrbomb, 0x10)
GET_ENEMY_PARAM_IMPL(zankibblecutter, 0x74)
GET_ENEMY_PARAM_IMPL(bonkersbomb, 0x60)
GET_ENEMY_PARAM_IMPL(dubiorspark, 0x4)
GET_ENEMY_PARAM_IMPL(mbossdead, 0x34)
